---
abstract: 'A template-free demo of CGI::Snapp using Log::Handler::Plugin::DBI'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Snapp-Demo-Four
provides:
  CGI::Snapp::Demo::Four:
    file: lib/CGI/Snapp/Demo/Four.pm
    version: 1.02
  CGI::Snapp::Demo::Four::Wrapper:
    file: lib/CGI/Snapp/Demo/Four/Wrapper.pm
    version: 1.02
requires:
  CGI: 3
  CGI::Emulate::PSGI: 0.14
  CGI::Snapp: 1.03
  Config::Plugin::Tiny: 1.01
  File::Spec: 0.86
  File::Temp: 0.14
  Hash::FieldHash: 0.12
  Log::Handler::Plugin::DBI: 1
  parent: 0
  strict: 1.03
  warnings: 1.03
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.02
